apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: girus
  name: rsscloud
spec:
  containers:
  - image: nginx
    name: girus
  - image: alpine
    name: strigus
    args:
    - sleep
    - "1800"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
