apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: girus
  name: girus
spec:
  containers:
  - image: nginx
    name: nginx
  - image: busybox
    name: busybox
    args:
    - sleep
    - "300"      
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
